[package]
name = "rproxy-api"
version = "0.0.1"
edition = "2021"
authors = ["touka shiro / max3584 <max3584.work@gmail.com>"]
description = "Platform independent asynchronous UDP/TCP proxy"
homepage = "https://github.com/max3584/rproxy-api"
repository = "https://github.com/max3584/rproxy-api"
readme = "README.md"
keywords = ["proxy", "TCP", "UDP", "async","openvpn"]
categories = ["command-line-utilities", "network-programming"]
license = "MIT"
exclude = [
    ".gitignore",
    "Cargo.toml.orig",
    "Cargo.lock",
]

[package.metadata]
fork_repository = "https://github.com/glacierx/rproxy"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
axum = "0.8"
axum-server = { version = "0.7", features = ["tls-rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
tracing-appender = "0.2"
socket2 = { version = "0.5", features = ["all"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "mysql"] }
argh = "0.1"

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json"] }
